"""upgrades.py — Toutes les ameliorations disponibles au level-up."""

# ── Stats globales ──
STAT_UPGRADES = [
    {"id":"hp_up",   "nom":"+20 PV max",       "desc":"Augmente PV max de 20 et soigne de 20.",
     "type":"stat",  "apply": lambda p:(setattr(p,"max_hp",p.max_hp+20), setattr(p,"hp",min(p.max_hp+20,p.hp+20)))},
    {"id":"spd_up",  "nom":"+Vitesse",          "desc":"Deplacement 12% plus rapide.",
     "type":"stat",  "apply": lambda p: setattr(p,"speed",p.speed*1.12)},
    {"id":"dmg_up",  "nom":"+3 Degats",         "desc":"Toutes les armes +3 degats de base.",
     "type":"stat",  "apply": lambda p: setattr(p,"bonus_dmg",p.bonus_dmg+3)},
    {"id":"cd_up",   "nom":"Vitesse d'attaque", "desc":"Toutes les armes 15% plus rapides.",
     "type":"stat",  "apply": lambda p: setattr(p,"atk_speed_mult",p.atk_speed_mult*0.85)},
    {"id":"area_up", "nom":"+Zone",             "desc":"Zone de toutes les armes +20%.",
     "type":"stat",  "apply": lambda p: setattr(p,"area_mult",p.area_mult*1.20)},
    {"id":"crit_up", "nom":"+Critique",         "desc":"Chance de critique +10% (x2 degats).",
     "type":"stat",  "apply": lambda p: setattr(p,"crit_chance",min(0.75,p.crit_chance+0.10))},
    {"id":"regen",   "nom":"Regeneration",      "desc":"+2 PV par seconde.",
     "type":"stat",  "apply": lambda p: setattr(p,"regen_rate",p.regen_rate+2.0)},
    {"id":"pickup",  "nom":"+Rayon XP",         "desc":"Rayon de ramassage des gemmes +50px.",
     "type":"stat",  "apply": lambda p: setattr(p,"pickup_radius",p.pickup_radius+50)},
    {"id":"xp_mult", "nom":"Double XP",         "desc":"Toutes les gemmes valent 2x plus.",
     "type":"stat",  "apply": lambda p: setattr(p,"xp_mult",p.xp_mult*2)},
    {"id":"proj_spd","nom":"+Vitesse proj.",    "desc":"Projectiles 20% plus rapides.",
     "type":"stat",  "apply": lambda p: setattr(p,"proj_speed_mult",p.proj_speed_mult*1.20)},
]

# ── Nouvelles armes (debloquables) ──
NEW_WEAPON_UPGRADES = [
    {"id":"nw_faux",     "nom":"Nouvelle arme : Faux",    "desc":"Coup large + saignement.",
     "type":"new_weapon","weapon_id":"faux"},
    {"id":"nw_fouet",    "nom":"Nouvelle arme : Fouet",   "desc":"Traverse tous les ennemis.",
     "type":"new_weapon","weapon_id":"fouet"},
    {"id":"nw_ail",      "nom":"Nouvelle arme : Ail",     "desc":"Zone + poison permanent.",
     "type":"new_weapon","weapon_id":"ail"},
    {"id":"nw_marteau",  "nom":"Nouvelle arme : Marteau", "desc":"Enorme zone + knockback.",
     "type":"new_weapon","weapon_id":"marteau"},
    {"id":"nw_bible",    "nom":"Nouvelle arme : Bible",   "desc":"3 bibles orbitantes.",
     "type":"new_weapon","weapon_id":"bible"},
    {"id":"nw_bouclier", "nom":"Nouvelle arme : Bouclier","desc":"2 boucliers tournants.",
     "type":"new_weapon","weapon_id":"bouclier"},
    {"id":"nw_couteau",  "nom":"Nouvelle arme : Couteau", "desc":"Couteaux rapides.",
     "type":"new_weapon","weapon_id":"couteau"},
    {"id":"nw_arc",      "nom":"Nouvelle arme : Arc",     "desc":"Fleche qui traverse.",
     "type":"new_weapon","weapon_id":"arc"},
    {"id":"nw_baguette", "nom":"Nouvelle arme : Baguette","desc":"Orbe explosif.",
     "type":"new_weapon","weapon_id":"baguette"},
    {"id":"nw_foudre",   "nom":"Nouvelle arme : Foudre",  "desc":"Chaine sur 4 ennemis.",
     "type":"new_weapon","weapon_id":"foudre"},
]

# ── Ameliorations par arme (5 niveaux, 2 choix chacun) ──
def _m(wid, lvl, id_a, nom_a, desc_a, fn_a, id_b, nom_b, desc_b, fn_b):
    return [
        {"id":id_a,"nom":nom_a,"desc":desc_a,"type":"weapon_upgrade","weapon":wid,"level":lvl+1,"apply":fn_a},
        {"id":id_b,"nom":nom_b,"desc":desc_b,"type":"weapon_upgrade","weapon":wid,"level":lvl+1,"apply":fn_b},
    ]

WEAPON_UPGRADES = {
    "epee": [
        _m("epee",0,"e1a","+2 Degats","Lame affilee.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+2),
                    "e1b","-10% CD",  "Plus rapide.", lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.9)),
        _m("epee",1,"e2a","+Zone +20%","Arc plus large.",lambda p:setattr(p,"area_mult",p.area_mult*1.2),
                    "e2b","+5 Degats","Acier trempe.", lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+5)),
        _m("epee",2,"e3a","Lame a deux mains","+8 degats, -20% cd.",
           lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+8),setattr(p,"atk_speed_mult",p.atk_speed_mult*0.8)),
                    "e3b","Lame de feu","Ajoute brulure 3s.",lambda p:p.weapon_mods.update({"epee_burn":True})),
        _m("epee",3,"e4a","Lame sainte","+10 degats + zone x1.3.",
           lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+10),setattr(p,"area_mult",p.area_mult*1.3)),
                    "e4b","Frappe eclair","-25% CD.",lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.75)),
        _m("epee",4,"e5a","Epee legendaire","+15 degats.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+15),
                    "e5b","Omnislash","Double attaque.",lambda p:p.weapon_mods.update({"epee_double":True})),
    ],
    "faux": [
        _m("faux",0,"fx1a","+Saignement","Saigne 5s.",lambda p:p.weapon_mods.update({"faux_bleed_dur":5000}),
                    "fx1b","+3 Degats","Lame tranchante.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+3)),
        _m("faux",1,"fx2a","+Arc large","Zone x1.3.",lambda p:setattr(p,"area_mult",p.area_mult*1.3),
                    "fx2b","+6 Degats","Tranchant max.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+6)),
        _m("faux",2,"fx3a","Faux spectrale","Traverse les ennemis.",lambda p:p.weapon_mods.update({"faux_pierce":True}),
                    "fx3b","+8 Degats","Acier noir.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+8)),
        _m("faux",3,"fx4a","Mort subite","5% chance de tuer instantanement.",lambda p:p.weapon_mods.update({"faux_instakill":True}),
                    "fx4b","-20% CD","Faux rapide.",lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.8)),
        _m("faux",4,"fx5a","Faux legendaire","+20 degats.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+20),
                    "fx5b","Grim Reaper","Saignement x2 + zone x1.5.",
                    lambda p:(p.weapon_mods.update({"faux_bleed_dur":8000}),setattr(p,"area_mult",p.area_mult*1.5))),
    ],
    "fouet": [
        _m("fouet",0,"fw1a","+Portee","Fouet +30px.",lambda p:p.weapon_mods.update({"fouet_range":p.weapon_mods.get("fouet_range",0)+30}),
                    "fw1b","+4 Degats","Claque plus fort.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+4)),
        _m("fouet",1,"fw2a","Double claque","Frappe 2x par activation.",lambda p:p.weapon_mods.update({"fouet_double":True}),
                    "fw2b","+8 Degats","Fouet de fer.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+8)),
        _m("fouet",2,"fw3a","Electrique","Etourdit 1s.",lambda p:p.weapon_mods.update({"fouet_stun":True}),
                    "fw3b","-15% CD","Reflexes vifs.",lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.85)),
        _m("fouet",3,"fw4a","Fouet de feu","Brule les ennemis.",lambda p:p.weapon_mods.update({"fouet_burn":True}),
                    "fw4b","+Zone","Portee x1.4.",lambda p:setattr(p,"area_mult",p.area_mult*1.4)),
        _m("fouet",4,"fw5a","Fouet legendaire","+15 degats.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+15),
                    "fw5b","Tempete","3 claquements par activation.",lambda p:p.weapon_mods.update({"fouet_triple":True})),
    ],
    "ail": [
        _m("ail",0,"a1a","+Zone","Nuage +25%.",lambda p:setattr(p,"area_mult",p.area_mult*1.25),
                    "a1b","Poison fort","Poison 2x plus fort.",lambda p:p.weapon_mods.update({"ail_poison2":True})),
        _m("ail",1,"a2a","+3 Degats","Ail concentre.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+3),
                    "a2b","-20% CD","Nuage permanent.",lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.8)),
        _m("ail",2,"a3a","Ralentisseur","Ralentit les ennemis 30%.",lambda p:p.weapon_mods.update({"ail_slow":True}),
                    "a3b","+Zone x1.3","Grande surface.",lambda p:setattr(p,"area_mult",p.area_mult*1.3)),
        _m("ail",3,"a4a","Ail maudit","Ajoute vulnerabilite (+20% degats recus).",lambda p:p.weapon_mods.update({"ail_vuln":True}),
                    "a4b","+6 Degats","Concentration max.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+6)),
        _m("ail",4,"a5a","Ail legendaire","Zone x2 + poison.",lambda p:(setattr(p,"area_mult",p.area_mult*2),p.weapon_mods.update({"ail_poison2":True})),
                    "a5b","Nuage mortel","+10 degats -30% CD.",lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+10),setattr(p,"atk_speed_mult",p.atk_speed_mult*0.7))),
    ],
    "marteau": [
        _m("marteau",0,"mh1a","+Knockback","Repousse 2x plus loin.",lambda p:p.weapon_mods.update({"marteau_kb2":True}),
                    "mh1b","+5 Degats","Marteau lourd.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+5)),
        _m("marteau",1,"mh2a","+Zone +30%","Impact plus large.",lambda p:setattr(p,"area_mult",p.area_mult*1.3),
                    "mh2b","+8 Degats","Frappe devastatrice.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+8)),
        _m("marteau",2,"mh3a","Onde de choc","Emet 4 projectiles a l'impact.",lambda p:p.weapon_mods.update({"marteau_wave":True}),
                    "mh3b","-20% CD","Marteau leger.",lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.8)),
        _m("marteau",3,"mh4a","Saut+Frappe","Zone x1.5.",lambda p:setattr(p,"area_mult",p.area_mult*1.5),
                    "mh4b","+12 Degats","Force titanesque.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+12)),
        _m("marteau",4,"mh5a","Marteau legendaire","+20 degats + onde.",
           lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+20),p.weapon_mods.update({"marteau_wave":True})),
                    "mh5b","Devastation","Zone x2 -25% CD.",
                    lambda p:(setattr(p,"area_mult",p.area_mult*2),setattr(p,"atk_speed_mult",p.atk_speed_mult*0.75))),
    ],
    "bible": [
        _m("bible",0,"bi1a","+1 Bible","4 bibles en orbite.",lambda p:p.weapon_mods.update({"bible_count":p.weapon_mods.get("bible_count",3)+1}),
                    "bi1b","+Vitesse","Orbite 30% plus rapide.",lambda p:p.weapon_mods.update({"bible_speed":p.weapon_mods.get("bible_speed",2.5)*1.3})),
        _m("bible",1,"bi2a","+3 Degats","Bibles renforcees.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+3),
                    "bi2b","+Rayon","Orbite +20px.",lambda p:p.weapon_mods.update({"bible_radius":p.weapon_mods.get("bible_radius",90)+20})),
        _m("bible",2,"bi3a","Bibles de feu","Brulent au contact.",lambda p:p.weapon_mods.update({"bible_burn":True}),
                    "bi3b","+1 Bible","5 bibles.",lambda p:p.weapon_mods.update({"bible_count":p.weapon_mods.get("bible_count",3)+1})),
        _m("bible",3,"bi4a","Bibles saintes","+8 degats.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+8),
                    "bi4b","Bibles eclair","Etourdissent 0.5s.",lambda p:p.weapon_mods.update({"bible_stun":True})),
        _m("bible",4,"bi5a","Bible legendaire","+12 degats + 6 bibles.",
           lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+12),p.weapon_mods.update({"bible_count":6})),
                    "bi5b","Croix divine","Zone +50% + vitesse +50%.",
                    lambda p:(setattr(p,"area_mult",p.area_mult*1.5),p.weapon_mods.update({"bible_speed":p.weapon_mods.get("bible_speed",2.5)*1.5}))),
    ],
    "bouclier": [
        _m("bouclier",0,"sh1a","+Degats","Boucliers +5 degats.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+5),
                    "sh1b","+Vitesse","Rotation 25% plus rapide.",lambda p:p.weapon_mods.update({"shield_speed":p.weapon_mods.get("shield_speed",1.8)*1.25})),
        _m("bouclier",1,"sh2a","+1 Bouclier","3 boucliers.",lambda p:p.weapon_mods.update({"shield_count":p.weapon_mods.get("shield_count",2)+1}),
                    "sh2b","Reflet","Renvoie les projectiles.",lambda p:p.weapon_mods.update({"shield_reflect":True})),
        _m("bouclier",2,"sh3a","Bouclier electrique","Etourdissement.",lambda p:p.weapon_mods.update({"shield_stun":True}),
                    "sh3b","+8 Degats","Boucliers d'acier.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+8)),
        _m("bouclier",3,"sh4a","+Rayon","Orbite +30px.",lambda p:p.weapon_mods.update({"shield_radius":p.weapon_mods.get("shield_radius",70)+30}),
                    "sh4b","4 Boucliers","Couverture totale.",lambda p:p.weapon_mods.update({"shield_count":4})),
        _m("bouclier",4,"sh5a","Bouclier legendaire","+15 degats + 4 boucliers.",
           lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+15),p.weapon_mods.update({"shield_count":4})),
                    "sh5b","Aegide divine","Reflet + etourdissement + vitesse x1.5.",
                    lambda p:(p.weapon_mods.update({"shield_reflect":True,"shield_stun":True,"shield_speed":p.weapon_mods.get("shield_speed",1.8)*1.5}))),
    ],
    "couteau": [
        _m("couteau",0,"kn1a","+1 Couteau","2 couteaux par tir.",lambda p:p.weapon_mods.update({"couteau_count":p.weapon_mods.get("couteau_count",1)+1}),
                    "kn1b","-10% CD","Lancers plus rapides.",lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.9)),
        _m("couteau",1,"kn2a","+2 Couteaux","3 couteaux par tir.",lambda p:p.weapon_mods.update({"couteau_count":p.weapon_mods.get("couteau_count",1)+2}),
                    "kn2b","+3 Degats","Couteaux affutes.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+3)),
        _m("couteau",2,"kn3a","Couteaux percants","Traversent les ennemis.",lambda p:p.weapon_mods.update({"couteau_pierce":True}),
                    "kn3b","-20% CD","Virtuose.",lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.8)),
        _m("couteau",3,"kn4a","Couteaux en eventail","5 directions.",lambda p:p.weapon_mods.update({"couteau_fan":True}),
                    "kn4b","+6 Degats","Lames de maître.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+6)),
        _m("couteau",4,"kn5a","Couteau legendaire","+10 degats + 5 couteaux percants.",
           lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+10),p.weapon_mods.update({"couteau_count":5,"couteau_pierce":True})),
                    "kn5b","Pluie de couteaux","-30% CD + eventail.",
                    lambda p:(setattr(p,"atk_speed_mult",p.atk_speed_mult*0.7),p.weapon_mods.update({"couteau_fan":True}))),
    ],
    "arc": [
        _m("arc",0,"ar1a","+Pierce","Traverse 3 ennemis.",lambda p:p.weapon_mods.update({"arc_pierce":p.weapon_mods.get("arc_pierce",2)+1}),
                    "ar1b","+5 Degats","Arc de guerre.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+5)),
        _m("arc",1,"ar2a","Double fleche","2 fleches par tir.",lambda p:p.weapon_mods.update({"arc_double":True}),
                    "ar2b","+8 Degats","Arc lourd.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+8)),
        _m("arc",2,"ar3a","Triple fleche","3 fleches en eventail.",lambda p:p.weapon_mods.update({"arc_triple":True}),
                    "ar3b","+Vitesse +30%","Fleches plus rapides.",lambda p:setattr(p,"proj_speed_mult",p.proj_speed_mult*1.3)),
        _m("arc",3,"ar4a","Fleche explosive","Explose a l'impact.",lambda p:p.weapon_mods.update({"arc_explode":True}),
                    "ar4b","+12 Degats","Arc titanesque.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+12)),
        _m("arc",4,"ar5a","Arc legendaire","+15 degats + triple + explose.",
           lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+15),p.weapon_mods.update({"arc_triple":True,"arc_explode":True})),
                    "ar5b","Pluie de fleches","5 fleches + pierce.",
                    lambda p:(p.weapon_mods.update({"arc_rain":True,"arc_pierce":4}))),
    ],
    "baguette": [
        _m("baguette",0,"bg1a","Explosion +","Zone d'explosion x1.3.",lambda p:setattr(p,"area_mult",p.area_mult*1.3),
                    "bg1b","+6 Degats","Orbe concentre.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+6)),
        _m("baguette",1,"bg2a","Double orbe","2 orbes par tir.",lambda p:p.weapon_mods.update({"bag_double":True}),
                    "bg2b","-15% CD","Magie rapide.",lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.85)),
        _m("baguette",2,"bg3a","Orbe de feu","Brule + explosion.",lambda p:p.weapon_mods.update({"bag_burn":True}),
                    "bg3b","+10 Degats","Puissance magique.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+10)),
        _m("baguette",3,"bg4a","Quadruple orbe","4 directions.",lambda p:p.weapon_mods.update({"bag_quad":True}),
                    "bg4b","Orbe glacant","Ralentit les ennemis.",lambda p:p.weapon_mods.update({"bag_slow":True})),
        _m("baguette",4,"bg5a","Baguette legendaire","+20 degats + quad + explose.",
           lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+20),p.weapon_mods.update({"bag_quad":True,"bag_burn":True})),
                    "bg5b","Nova magique","8 orbes en etoile.",lambda p:p.weapon_mods.update({"bag_nova":True})),
    ],
    "foudre": [
        _m("foudre",0,"fl1a","+Chaines","Chaine sur 5 ennemis.",lambda p:p.weapon_mods.update({"foudre_chain":p.weapon_mods.get("foudre_chain",3)+2}),
                    "fl1b","+5 Degats","Foudre intense.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+5)),
        _m("foudre",1,"fl2a","Etourdissement","Etourdit 1.5s.",lambda p:p.weapon_mods.update({"foudre_stun":True}),
                    "fl2b","-15% CD","Tempete electrique.",lambda p:setattr(p,"atk_speed_mult",p.atk_speed_mult*0.85)),
        _m("foudre",2,"fl3a","Double eclair","2 eclairs par tir.",lambda p:p.weapon_mods.update({"foudre_double":True}),
                    "fl3b","+8 Degats","Puissance supreme.",lambda p:setattr(p,"bonus_dmg",p.bonus_dmg+8)),
        _m("foudre",3,"fl4a","Tempete","+Vitesse +30%.",lambda p:setattr(p,"proj_speed_mult",p.proj_speed_mult*1.3),
                    "fl4b","Surtension","Chaine sur 8 ennemis.",lambda p:p.weapon_mods.update({"foudre_chain":8})),
        _m("foudre",4,"fl5a","Foudre legendaire","+15 degats + 8 chaines + etourd.",
           lambda p:(setattr(p,"bonus_dmg",p.bonus_dmg+15),p.weapon_mods.update({"foudre_chain":8,"foudre_stun":True})),
                    "fl5b","Orage divin","3 eclairs + double.",
                    lambda p:(p.weapon_mods.update({"foudre_double":True}),setattr(p,"atk_speed_mult",p.atk_speed_mult*0.6))),
    ],
}
